### ISSUE TITLE
Add "Are you connected to the VPN?" to the QA script

### ISSUE THREAD

**Issue by nottrobin** [canonical-webteam/deployment-configs#32]
The QA script will let you happily try to deploy even if you're not connected to the VPN, but then the container will just hang when trying to pull the image.

We should maybe add a step that says "Are you connected to the VPN? Y/n"

**Comment by tbille** [comment]
Done with this pr https://github.com/canonical-webteam/deployment-configs/pull/29

**Comment by nottrobin** [comment]
Actually, I mistakenly thought we needed to be connected to the VPN to access the registry. It seems this is not in fact the case. So we didn't even need this :laughing: but don't bother removing it.
